pipeline {
    agent any

    environment {
        CSL_CI = '1'

        VERSION_TYPE = 'stable'
        MICROSOFT_AUTH_ID = credentials('microsoft_auth_id')
        CURSEFORGE_API_KEY = credentials('curseforge_api_key')
        CSL_SIGNATURE_KEY = credentials('csl_signature_key')
    }

    stages {
        stage('Build') {
            steps {
                sh 'bash ./config/jenkins/config-jenkins.sh'
                sh './gradlew clean makeExecutables makeDeb --stacktrace --no-daemon'
                archiveArtifacts artifacts: 'CSL/build/libs/*'
            }
        }
    }
}
